config/routes.rb
NewName::Application.routes.draw do
  resources :relationships

  resources :ribbits

  resources :users

  root to: 'ribbits#index'

  get 'buddies', to: 'users#buddies', as: 'buddies'

  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id

  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

end

app/models/ribbit.rb
class Ribbit < ActiveRecord::Base
  default_scope order: 'created_at DESC'
  attr_accessible :content, :user_id
  belongs_to :user
  validates :content, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :avatar_url, :email, :name, :password, :password_confirmation, :username
  has_secure_password
  has_many :ribbits

  has_many :follower_relationships, class_name: 'Relationship', foreign_key: 'followed_id'
  has_many :followed_relationships, class_name: 'Relationship', foreign_key: 'follower_id'

  has_many :followers, through: :follower_relationships
  has_many :followeds, through: :followed_relationships

  before_validation :prep_email
  before_save :create_avatar_url

  validates :name, presence: true
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true, format: { with: /^[\w.+-]+@([\w]+.)+\w+$/ }

  def following? user
    self.followeds.include? user
  end
  def follow user
    Relationship.create follower_id: self.id, followed_id: user.id
  end

  private
  def prep_email
  	self.email = self.email.strip.downcase if self.email
  end

  def create_avatar_url
  	self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		@relationship = Relationship.new
        @relationship.followed_id = params[:followed_id]
        @relationship.follower_id = current_user.id
	    if @relationship.save
	        redirect_to User.find params[:followed_id]
	    else
	        flash[:error] = "Couldn't Follow"
	        redirect_to root_url
	    end
	end

	def destroy
		@relationship = Relationship.find(params[:id])
    	@relationship.destroy
    	redirect_to user_path params[:id]
	end
end

app/controllers/ribbits_controller.rb
class RibbitsController < ApplicationController
	def create
		@ribbit = Ribbit.new(params[:ribbit])
		@ribbit.user_id = current_user.id
		if @ribbit.save
			redirect_to current_user
		else
			flash[:error] = 'Problem!'
			redirect_to current_user
		end
	end

	def index
		@ribbits = Ribbit.all include: :user
		@ribbit = Ribbit.new
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	user = User.find_by_username(params[:username])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to root_url, notice: 'Logged in!'
  	else
  		flash[:error] = 'Wrong Username or Password.'
  		redirect_to root_url
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: 'Logged out.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new
		if current_user
			redirect_to buddies_path
		else
			@user = User.new
		end
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			session[:user_id] = @user.id
			redirect_to @user, notice: 'Thank you for signing up to Smitter'
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
		@ribbit = Ribbit.new
		@relationship = Relationship.where(
		    follower_id: current_user.id,
		    followed_id: @user.id
		).first_or_initialize if current_user
	end

	def edit
	end

	def update
	end

	def destroy
	end

	def buddies
	    if current_user
	        @ribbit = Ribbit.new
	        buddies_ids = current_user.followeds.map(&:id).push(current_user.id)
	        @ribbits = Ribbit.find_all_by_user_id buddies_ids
	    else
	        redirect_to root_url
	    end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/ribbits_helper.rb
module RibbitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet/less" href="/style.less">
    <script src="/less.js"></script>
    <title>&middot;Smitter &middot;Jurgens Smit</title>
    <meta name="description" content="Personal project of Jurgens Smit – Ruby on Rails developer.">
    <meta name="keywords" content="Ruby, Rails, Ruby on Rails, web designer, back end developer, Jurgens Smit, sydney, front end developer, Javascript, HTML, CSS" />
<meta name="author" content="Jurgens Smit">
</head>
<body>
    <header>
        <div class="wrapper">
            <a href='<%= root_url %>'></a>
            <a href="/" class="brand"><strong>SMITTER</a></strong> |
          

                <%= link_to "Public Smitters", ribbits_path %>
                -
                <%= link_to "Public Profiles", users_path %>
                -
                <%= link_to "Buddies' Smitters", buddies_path %>
                -
                <%= link_to "My Profile", current_user %>
                -
        		<%= link_to "Log Out", sessions_destroy_path %>

        </div>
        
    </header>
    <div id="content">
        <div class="wrapper">
            <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, class: "flash #{name}" %>
            <% end %>
            <%= yield %>
        </div>
    </div>
    <footer>
        <div class="wrapper">
            Smitter. Better than Twitter.
        </div>
    </footer>
</body>
</html>

app/views/ribbits/index.html.erb
<% if current_user %>
<div id="createRibbit" class="panel right">
    <h1>Create a Smitter</h1>
    <p>
    <%= form_for @ribbit do |f| %>
        <%= f.text_area :content, class: 'ribbitText' %>
        <%= f.submit "Smitter!" %>
    <% end %>
    </p>
</div>
<% end %>
<div class="panel left">
    <h1>Public Smitters</h1>
    <% @ribbits.each do |ribbit| %>
        <div class="ribbitWrapper">
            <a href="<%= user_path ribbit.user %>">
            <img class="avatar" src="<%= ribbit.user.avatar_url %>">
            <span class="name"><%= ribbit.user.name %></span>
            </a>
            @<%= ribbit.user.username %>
            <span class="time"><%= time_ago_in_words(ribbit.created_at) %></span>
            <p> <%= ribbit.content %> </p>
        </div>
    <% end %>
</div>

app/views/users/buddies.html.erb
<% if current_user %>
<div id="createRibbit" class="panel right">
    <h1>Create a Smitter</h1>
    <p>
    <%= form_for @ribbit do |f| %>
        <%= f.text_area :content, class: 'ribbitText' %>
        <%= f.submit "Smitter!" %>
    <% end %>
    </p>
</div>
<% end %>
<div class="panel left">
    <h1>Buddies' Smitters</h1>
    <% @ribbits.each do |ribbit| %>
        <div class="ribbitWrapper">
            <a href="<%= user_path ribbit.user %>">
            <img class="avatar" src="<%= ribbit.user.avatar_url %>">
            <span class="name"><%= ribbit.user.name %></span>
            </a>
            @<%= ribbit.user.username %>
            <span class="time"><%= time_ago_in_words(ribbit.created_at) %></span>
            <p> <%= ribbit.content %> </p>
        </div>
    <% end %>
</div>

app/views/users/index.html.erb
<div id='ribbits' class='panel left'>
	<h1>Public Profile</h1>
    <% @users.each do |user| %>
    <div class="ribbitWrapper">
        <a href="<%= user_path user %>">
        <img class="avatar" src="<%= user.avatar_url %>">
        <span class="name"><%= user.name %></span>
        </a>
        @<%= user.username %>
        <p>
        <%= user.ribbits.size %> Smitters
        <span class="spacing"><%= user.followers.count %> Followers</span>
        <span class="spacing"><%= user.followeds.count %> Following</span>
        </p>
        <% if user.ribbits.first %>
        	<p><%= user.ribbits.first.content %></p>
        <% end %>
    </div>
    <% end %>
</div>

app/views/users/new.html.erb
<img src='gfx/frog.jpg'>
<div class='panel right'>
	<h1>New to Smitter?</h1>
	<%= form_for @user do |f| %>
		<% if @user.errors.any? %>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
		<%= f.text_field :email, placeholder: 'email' %>
		<%= f.text_field :username, placeholder: 'username' %>
		<%= f.text_field :name, placeholder: 'name' %>
		<%= f.text_field :password, placeholder: 'password' %>
		<%= f.text_field :password_confirmation, placeholder: 'password' %>
		<%= f.submit 'Create Account' %>
	<% end %>
</div>

app/views/users/show.html.erb
<% if current_user %>
<div id="createRibbit" class="panel right">
    <h1>Create a Smitter</h1>
    <p>
    <%= form_for @ribbit do |f| %>
        <%= f.text_area :content, class: 'ribbitText' %>
        <%= f.submit "Smitter!" %>
    <% end %>
    </p>
</div>
<% end %>
<div id="ribbits" class="panel left">
    <h1>Your Smitter Profile</h1>
    <div class="ribbitWrapper">
        <img class="avatar" src="<%= @user.avatar_url %>">
        <span class="name"><%= @user.name %></span> @<%= @user.username %>
        <p>
        <%= @user.ribbits.size %> Smitters
        <span class="spacing"><%= @user.followers.count %> Followers</span>
        <span class="spacing"><%= @user.followeds.count %> Following</span>
        <% if current_user and @user != current_user %>
            <% if current_user.following? @user %>
                <%= form_tag relationship_path, method: :delete do %>
                    <%= submit_tag "Unfollow" %>
                <% end %>
            <% else %>
                <%= form_for @relationship do %>
                    <%= hidden_field_tag :followed_id, @user.id %>
                    <%= submit_tag "Follow" %>
                <% end %>
            <% end %>
        <% end %>
        </p>
    </div>
</div>
<div class="panel left">
    <h1>Your Smitters</h1>
    <% @user.ribbits.each do |ribbit| %>
        <div class="ribbitWrapper">
            <img class="avatar" src="<%= @user.avatar_url %>">
            <span class="name"><%= @user.name %></span>
            @<%= @user.username %>
            <span class="time"><%= time_ago_in_words(ribbit.created_at) %></span>
            <p> <%= ribbit.content %> </p>
        </div>
    <% end %>
</div>